{% set name = "jsonref" %}
{% set version = "1.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/gazpachoking/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0b18f471956f60adc4cabed25fd8563237f81f2d5107e0cd0b4058110f2be100

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "
  noarch: python

requirements:
  host:
    - pip
    - pdm-backend
    - pdm-pep517
    - python >=3.7
  run:
    - python >=3.7

test:
  source_files:
    - tests
  requires:
    - pytest >=7.1.3
  imports:
    - jsonref
  commands:
    - pytest

about:
  home: http://github.com/gazpachoking/jsonref
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An implementation of JSON Reference for Python

extra:
  recipe-maintainers:
    - chapmanb
    - marcelotrevisani
