travis:
  secure:
    BINSTAR_TOKEN: lLxieCqQiEG+SSetWGl6zMVTiNhuNiccO6twT1uDCuHvCgoMqPLUy9vCvNyEFqRFzh8moCi2nCkt8iUtHgeowY5zYEkLW9WtxMwGjIasPsR1mTIkAADDDQnunM8Avm9vY4cE4eirRKRxXF7eF8PYr7V47vauE6PU7N1t7l2gbz8aO14r5pp7Xvchx7sTTd2THjDw0DW5cq3oHP7VRJb+wObfwxhz/ZAHiksXnnsyRLejLKhZCyK3UHyBA3rrWuRzrxqGmWeG089E+fhyOci8mmKftqigGpz97SdgqBnq1a/24pgpaKsRbjCmwLZVIOM70wTouZNn4DIVfzjjRDe+F+XArHgwrZezCcde+YIISjDIgm9SPmxLA95WzfwAO0qOlMVC8yy0yQVGDe4ouxXmyhK11g/3Ikr61L7TOxVnL2I2BxjZaVhowSBdEbG6IdNB5yanZMVSag+uQYQXz12Ls4AX3n6Iv1Jg43Tt/OPlUHUgI9azT0thNU+9A05PshdcTuHMGeEJ/mmx/m+7lS83qK2iNX35v8OvVOq/jU86/oPJXufftz6B+nuy3jHdQ9ZhXUuVZydCFKP366lloDTHp8sOXNAFUcwPOt4PKcsgeHWRxlSLxpIorm03Q2HHkgUt3wsf2r37txNP6YtOomifl4rmsD26geYBjcGgUJPeJX0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
